### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by changhaitravis** [uweb/uw-2014#11]
Hi, guys,
I'm from the UW Grant and Contract Accounting Department, and we're using your guys' new wordpress theme for our new Intranet. Our old intranet is very deprecated and early 2000s.

I've been able to modify your theme for our uses, however, I see that you guys keep doing bug fixes, and I just want to fix our codebase with a stable version or fork from a stable version. Everytime I merge my project back with your guys' to essentially receive "updates", there is a lot of code cleanup that needs to be done, and I can't determine whether merging is worth it.

can you take up tagging releases again?
I see that the only release is 0.8 which was pretty much when you guys initially released.

**Comment by daneodekirk** [comment]
This has been requested more often lately since the theme's gained in popularity. We'll start tagging releases again. Thanks for the input.

**Comment by druginteractioninfo-org** [comment]
I see you tagged a 1.0.0 release on July 29th.  Are you going to be diligently tagging major and minor releases?

**Comment by nwinkelbauer** [comment]
We definitely want to tag major releases at a minimum so people know which versions are most stable if they don't plan on updating their website. We are currently working on figuring out what constitutes a major or minor release so that we can figure out how we want that process to look. We want to make sure our major releases are stable and without bugs, so those will be spread out a lot and most likely come before any big feature releases. So far we are thinking of only using minor releases with features and important bug fixes, but those details are currently in the works. Any insight or feedback is much appreciated though if you have any ideas.

**Comment by chriskinsella** [comment]
Use the MAJOR.MINOR.PATCH versioning as defined by Semantic Versioning http://semver.org/  This is the versioning that basically everything uses today.  This is a core assumption made by npm, bower, and pretty much all package managers.  

I'd recommend **strictly** following Semantic Versioning as it will simplify/unify your team's understanding of versioning as well as providing consumers of you code clear insight to the scale of each change.  It would be great to use npm outdated to check for new versions.

**Comment by Nogbit** [comment]
I second what @changhaitravis said regarding semver.  If you want all the schools and colleges to implement the theme they will need to trust this repo with anything that is a ``minor`` release being something they can simply pull down into their codebase without worry (new non breaking features/changes). Only do ``major`` releases when there are breaking changes along with a change log of what breaks of course.  And simple bug fixes would be a ``patch``.

With that said, and the fact that this is an old issue were there any decisions made on your team to follow semver?  It seems you are indicating that via your tags.

**Comment by lcaple** [comment]
The UWeb team has decided to follow semver more closely as we tag releases. Moving forward, expect the Major, Minor, and Patch release numbering to be followed.

Closing.
