### ISSUE TITLE
question regarding prefixing releases with v

### ISSUE THREAD

**Issue by jodytate** [uweb/uw-2014#126]
Regarding release tags, our team (in [UW's Office of Research Information Services](https://www.washington.edu/research/oris/)) is curious if there's a rationale driving when a `v` is used. For example, the most recent release is [1.4.9](https://github.com/uweb/uw-2014/releases/tag/1.4.9) but the release prior is [v1.4.9](https://github.com/uweb/uw-2014/releases/tag/v1.4.9). The two have the same version number, but contain different fixes. It could also be that 1.4.9 was intended to be v1.4.10 and a step was missed in the release process to increment as expected (as has happened to us on more than one occasion).

**Comment by lcaple** [comment]
It was a mistake from a missed pushed tag. I typically reference the remote github repository when increment, but the tag was never pushed from local to github. That's why there is a duplicate.

There's no rationale behind `v` other than I am trying to _not_ use it but a number of tags predating me used it. I have tried to stop using it completely, but sometimes it slips when I'm referencing the previous tags list.

**Comment by jodytate** [comment]
Thanks for such a quick response! This is helpful information to have. And I certainly understand how the mistake can happen, having done it myself. I'll close the issue as this resolves my question. Thanks again!
